# default_config.yml
# Default configuration for the OPM Control System
# Using the exact values from the original hardware_model.py

hardware:
  # Device labels
  galvo_a_label: "Scanner:AB:33"
  piezo_a_label: "PiezoStage:P:34"
  camera_a_label: "Camera-1"
  camera_b_label: "Camera-2"
  plogic_label: "PLogic:E:36"
  tiger_comm_hub_label: "TigerCommHub"

  # PLogic Address Constants (Decimal)
  plogic_trigger_ttl_addr: 41
  plogic_4khz_clock_addr: 192
  plogic_laser_on_cell: 10
  plogic_camera_cell: 11
  plogic_always_on_cell: 12
  plogic_bnc3_addr: 35

  # PLogic Calibration & Timing
  pulses_per_ms: 4.0
  plogic_laser_preset_num: 30
  slice_calibration_slope_um_per_deg: 100.0

  # Galvo/SPIM Timing
  line_scans_per_slice: 1
  delay_before_scan_ms: 0.0
  line_scan_duration_ms: 1.0
  delay_before_side_ms: 0.0

# Default acquisition settings
acquisition:
  num_slices: 3
  step_size_um: 1.0
  laser_trig_duration_ms: 10.0
  camera_exposure_ms: 10.0