# default_config.yml
# Default configuration for the OPM Control System

hardware:
  # Device labels
  tiger_comm_hub_label: "TigerCommHub"
  galvo_a_label: "Scanner:AB:33"
  piezo_a_label: "PiezoStage:P:34"
  plogic_label: "PLogic:E:36"
  camera_a_label: "Camera-1"
  camera_b_label: "Camera-2"

  # PLogic Address Constants (Decimal)
  plogic_trigger_ttl_addr: 41
  plogic_4khz_clock_addr: 192
  plogic_laser_on_cell: 10
  plogic_camera_cell: 11
  plogic_always_on_cell: 12
  plogic_bnc1_addr: 33
  plogic_bnc3_addr: 35

  # PLogic Calibration & Timing
  pulses_per_ms: 4.0
  plogic_laser_preset_num: 30
  slice_calibration_slope_um_per_deg: 100.0

  # PLogic Presets for Live/Snap
  plogic_live_mode_preset: 12
  plogic_idle_mode_preset: 10

  # Galvo/SPIM Static Settings
  galvo_static_params:
    BeamEnabled: "Yes"
    SPIMAlternateDirectionsEnable: "No"
    SPIMInterleaveSidesEnable: "No"
    SPIMPiezoHomeDisable: "No"
    SPIMNumSides: 1
    SPIMFirstSide: "A"
    "SingleAxisXAmplitude(deg)": 0.0
    "SingleAxisXOffset(deg)": 0.0
    "SingleAxisYOffset(deg)": 0.0
    SPIMNumSlicesPerPiezo: 1
    "SPIMDelayBeforeSide(ms)": 0.0
    "SPIMScanDuration(ms)": 1.0

# Default acquisition settings
acquisition:
  num_slices: 3
  step_size_um: 1.0
  laser_trig_duration_ms: 10.0
  camera_exposure_ms: 10.0
  galvo_amplitude_deg: 0.0
